### PR TITLE
Simplify declarative plugin application for multi-module builds

### PR DESCRIPTION
**Pull request by SUPERCILEX**
### Background

I know Gradle is trying to phase out the `buildscript` block, but I've seen many people get frustrated with the plugin management stuff. This especially becomes a nuisance when dealing with multi-module builds because:
1. It isn't necessary when using the plugin in a submodule
1. The number of plugins that need to be mapped explodes (just with Android, it's `com.android.application`, `com.android.library`, `com.android.dynamic-feature`, and `com.android.feature` which is absurd)
1. It makes managing versions harder since you have to specify a version each time you apply a plugin and change it everywhere

#### Original context

image

### Proposal

Keep the plugin management section for people with single-module projects. However, for the Android specific case, most everyone uses multi-module builds since that's what the Android Studio template starts you off with. In that case, show how to use the declarative style in submodules with the optional imperative style in the root module.

### CODE REVIEW

**Comment by SUPERCILEX** [comment]
@eskatos WDYT?

**Comment by SUPERCILEX** [comment]
@eskatos WDYT?

**Comment by eskatos** [comment]
Thank you for the PR @SUPERCILEX!
This aspect is now documented in the Kotlin DSL chapter of the Gradle user manual.
Here's a nightly rendered version https://docs.gradle.org/nightly/userguide/kotlin_dsl.html#sec::multi_project_builds
I agree that this strategy is simpler and easier to manage Today. I'll update the user manual in this regard.

**Comment by SUPERCILEX** [comment]
But is there an example with the Android plugin? I've noticed people straight up copying this guide.

**Comment by eskatos** [comment]
@SUPERCILEX, this should be addressed https://github.com/gradle/gradle/pull/7459

**Comment by SUPERCILEX** [comment]
Ok, SGTM 👍

**Pull request closed without merging**
